http_port 3128

cache_dir ufs /var/cache/squid 100 16 256

access_log /var/log/squid/access.log squid
cache_log /var/log/squid/cache.log

acl localnet src all
acl ipadmin src 192.168.60.253
acl ipadmin src 192.168.61.4

acl allowlink dstdomain .myip.com .iqos.com

http_access allow ipadmin
http_access deny all

visible_hostname squid-docker
